echo "_______First Test_____"
./compiler  "test_arithmetic.txt"
echo "_______Second Test_____"
./compiler -parse "test1.src"
echo "_______Third Test_____"
./compiler -parse "test2.src"
echo "_______Fourth Test_____"
./compiler -lex "test1.src"
echo "_______Fifth Test_____"
./compiler -lex "test2.src"
